jwt:
  secret:

spring:
  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      schema-locations: classpath:initializer/schema.sql
      mode: always
#      data-locations: classpath:initializer/data.sql

admin:
  id:
  password: